name: Upload Python Package

on:
  push:
    tags:
      - 'v0.2.1'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine bump2version

    - name: Bump version
      run: bump2version patch --allow-dirty

    - name: Build package
      run: python -m build

    - name: Check if package exists on PyPI
      id: check-package
      run: |
        PACKAGE_NAME="mihrab_ai_agent"
        VERSION=$(python setup.py --version)
        if twine check dist/${PACKAGE_NAME}-${VERSION}-py3-none-any.whl; then
          echo "Package ${PACKAGE_NAME}-${VERSION} already exists on PyPI"
          exit 1
        fi

    - name: Publish package
      if: steps.check-package.outcome != 'failure'
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: python -m twine upload dist/*
