name: Upload Python Package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Build package
      run: python -m build

    - name: Check if package exists on PyPI
      id: check-package
      run: |
        PACKAGE_NAME="mihrab_ai_agent"
        if twine check dist/${PACKAGE_NAME}-${VERSION}* && curl -s https://pypi.org/pypi/${PACKAGE_NAME}/${VERSION}/json > /dev/null; then
          echo "::set-output name=exists::true"
          echo "Package ${PACKAGE_NAME}-${VERSION} already exists on PyPI"
        else
          echo "::set-output name=exists::false"
        fi

    - name: Publish package
      if: steps.check-package.outputs.exists != 'true'
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: python -m twine upload dist/*
